[build]
builder = "railway:custom"
buildCommand = "cd kangmmf-bot && pip install -r requirements.txt"
startCommand = "cd kangmmf-bot && python bot.py"

[build.packs.python]
version = "3.11"

[build.packs.apt]
packages = [
  "ffmpeg",
  "fonts-dejavu-core"
]

[start]
cmd = "python bot.py"
